// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import { combineImportEntries, defaultImportEntries } from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { Text, RichText, Link, Image, Placeholder, useSitecore, CdpHelper } from '@sitecore-content-sdk/nextjs';
import { useState, useEffect } from 'react';
import React from 'react';
import * as React_7214d18997ee864dd178de7b3a8430f6783e8b89 from 'react';
import { Default } from 'src/components/vitality/ProductCard';
import { Text as Text_c75494e206654ce34c7e8236c30ae32a272f2d85, Link as Link_c75494e206654ce34c7e8236c30ae32a272f2d85, Image as Image_c75494e206654ce34c7e8236c30ae32a272f2d85, Placeholder as Placeholder_c75494e206654ce34c7e8236c30ae32a272f2d85 } from '@sitecore-content-sdk/react';
import { Search, User, X, ChevronDown, ChevronUp, Clock, Check, ChevronRight, Circle } from 'lucide-react';
import { FaFacebookF, FaLinkedin, FaInstagram, FaYoutube, FaTwitter } from 'react-icons/fa';
import * as SheetPrimitive from '@radix-ui/react-dialog';
import { cva } from 'class-variance-authority';
import { cn } from 'lib/utils';
import * as DropdownMenuPrimitive from '@radix-ui/react-dropdown-menu';
import { Slot } from '@radix-ui/react-slot';
import Head from 'next/head';
import client from 'lib/sitecore-client';
import Image_5d8ce56058442d94361877e28c501c951a554a6a from 'next/image';
import * as FEAAS from '@sitecore-feaas/clientside/react';
import nextConfig from 'next.config';
import { pageView } from '@sitecore-cloudsdk/events/browser';
import config from 'sitecore.config';

const importMap = [
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Text', value: Text },
      { name: 'RichText', value: RichText },
      { name: 'Link', value: Link },
      { name: 'Image', value: Image },
      { name: 'Placeholder', value: Placeholder },
      { name: 'useSitecore', value: useSitecore },
      { name: 'CdpHelper', value: CdpHelper },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'useState', value: useState },
      { name: 'useEffect', value: useEffect },
      { name: 'default', value: React },
      { name: '*', value: React_7214d18997ee864dd178de7b3a8430f6783e8b89 },
    ]
  },
  {
    module: 'src/components/vitality/ProductCard',
    exports: [
      { name: 'Default', value: Default },
    ]
  },
  {
    module: '@sitecore-content-sdk/react',
    exports: [
      { name: 'Text', value: Text_c75494e206654ce34c7e8236c30ae32a272f2d85 },
      { name: 'Link', value: Link_c75494e206654ce34c7e8236c30ae32a272f2d85 },
      { name: 'Image', value: Image_c75494e206654ce34c7e8236c30ae32a272f2d85 },
      { name: 'Placeholder', value: Placeholder_c75494e206654ce34c7e8236c30ae32a272f2d85 },
    ]
  },
  {
    module: 'lucide-react',
    exports: [
      { name: 'Search', value: Search },
      { name: 'User', value: User },
      { name: 'X', value: X },
      { name: 'ChevronDown', value: ChevronDown },
      { name: 'ChevronUp', value: ChevronUp },
      { name: 'Clock', value: Clock },
      { name: 'Check', value: Check },
      { name: 'ChevronRight', value: ChevronRight },
      { name: 'Circle', value: Circle },
    ]
  },
  {
    module: 'react-icons/fa',
    exports: [
      { name: 'FaFacebookF', value: FaFacebookF },
      { name: 'FaLinkedin', value: FaLinkedin },
      { name: 'FaInstagram', value: FaInstagram },
      { name: 'FaYoutube', value: FaYoutube },
      { name: 'FaTwitter', value: FaTwitter },
    ]
  },
  {
    module: '@radix-ui/react-dialog',
    exports: [
      { name: '*', value: SheetPrimitive },
    ]
  },
  {
    module: 'class-variance-authority',
    exports: [
      { name: 'cva', value: cva },
    ]
  },
  {
    module: 'lib/utils',
    exports: [
      { name: 'cn', value: cn },
    ]
  },
  {
    module: '@radix-ui/react-dropdown-menu',
    exports: [
      { name: '*', value: DropdownMenuPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-slot',
    exports: [
      { name: 'Slot', value: Slot },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: 'lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image_5d8ce56058442d94361877e28c501c951a554a6a },
    ]
  },
  {
    module: '@sitecore-feaas/clientside/react',
    exports: [
      { name: '*', value: FEAAS },
    ]
  },
  {
    module: 'next.config',
    exports: [
      { name: 'default', value: nextConfig },
    ]
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  }
];

export default combineImportEntries(defaultImportEntries, importMap);
